version: "3.8"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_NAME=matching_app
      - DB_PASSWORD=password
      - DB_USER=postgres
      - POSTGRES_PORT=5435
      - USER_TOKEN_SECRET=dummySecret

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5435:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=matching_app

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  data: {}
