FROM node:16.20.0-alpine3.17

WORKDIR /app

COPY package.json package-lock.json ./

RUN echo "node env ${NODE_ENV}"
RUN npm ci

COPY ./src ./src

RUN npm run build
RUN rm -R ./src
RUN rm ./package*

# start the app and run migrations
CMD node dist/index.js 

EXPOSE 4000