FROM node:16.20.0-alpine3.17

WORKDIR /app

COPY package.json package-lock.json ./

RUN echo "node env ${NODE_ENV}"
RUN npm ci

COPY ./src ./src

RUN npm run build
RUN node_modules/typeorm/cli.js migration:run -d dist/data-source.js
RUN rm -R ./src
RUN rm -R ./node_modules
RUN rm ./package*

CMD npm run start

EXPOSE 4000