version: "3.8"
services:
  api-prod:
    container_name: api-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_NAME=matching_app
      - DB_PASSWORD=password
      - DB_USER=postgres
      - POSTGRES_PORT=5435
      - USER_TOKEN_SECRET=dummySecret

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/data/db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=matching_app

volumes:
  postgres-data: {}

