FROM node:16.20.0-alpine3.17

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package.json package-lock.json ./

RUN echo "node env ${NODE_ENV}"
RUN npm ci

# no need to copy files because we are using volumes in docker-compose
# COPY . .

CMD npm run dev

EXPOSE 4000