version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - '${DB_PORT_HOST}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080


volumes: 
 data: {}