#!/usr/bin/env bash

set -e

export API_IMAGE="server-api:${1-latest}"

FIG="docker compose -f docker-compose.test.yml -p test"

$FIG kill
$FIG down --remove-orphans
$FIG run --rm \
    -v "${PWD}:/app" \
    api-test sh