#!/usr/bin/env bash

set -e

docker exec api npx typeorm-ts-node-commonjs schema:drop -d ./src/data-source.ts
docker exec api npx typeorm-ts-node-commonjs migration:run -d ./src/data-source.ts
docker exec api npm run ts -- ./src/seed-data/seed.ts