#!/usr/bin/env bash

set -e

docker exec -w /app/src api npx typeorm-ts-node-commonjs schema:drop -d ./data-source.ts
docker exec -w /app/src api npx typeorm-ts-node-commonjs migration:run -d ./data-source.ts
docker exec api npm run ts -- ./src/seed-data/seed.ts