FROM node:16.20.0-alpine3.17

ENV NODE_ENV=development

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

CMD ["yarn", "dev"]

# ENTRYPOINT ["tail", "-f", "/dev/null"]