# Use an official Node runtime as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install production dependencies
RUN yarn install --frozen-lockfile --production

# Copy the rest of the application code
COPY . .

# Build the TypeScript project
RUN yarn dist

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["node", "dist/src/index.js"]