version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_NAME=matching_app
      - DB_PASSWORD=password
      - DB_USER=postgres
      - POSTGRES_PORT=5435
      - USER_TOKEN_SECRET=dummySecret

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=matching_app

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  postgres-data: {}

