FROM node:20-alpine3.17

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY src tsconfig.json prisma credentials ./

RUN rm seed.ts

ENTRYPOINT ["tail", "-f", "/dev/null"]

# RUN yarn dist

# CMD node dist/index.js 

# EXPOSE 80