version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - $API_HOST_PORT:$API_CONTAINER_PORT
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: ./.env
    environment:
      - PORT=$API_HOST_PORT
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - POSTGRES_PORT=$DB_HOST_PORT
      - USER_TOKEN_SECRET=$API_USER_TOKEN_SECRET
      - TENCENT_COS_SECRET_ID=$TENCENT_COS_SECRET_ID
      - TENCENT_COS_SECRET_KEY=$TENCENT_COS_SECRET_KEY
      - TENCENT_COS_BUCKET=$TENCENT_COS_BUCKET
      - TENCENT_COS_REGION=$TENCENT_COS_REGION

  db:
    container_name: db
    image: postgres:15
    env_file: ./.env
    ports:
      - $DB_HOST_PORT:$DB_CONTAINER_PORT
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080

volumes:
  postgres-data: {}

